FORMAT: 1A

# travellerct

Travellerct is a simple API for generating, modifying, saving, and retrieving Classic Traveller (CT) role playing game data.

## Character Collection [/characters]

### List All Characters [GET]

List full detail on all characters.
The universal personality profile (UPP) is represented by an integer from 1 to 14.

+ Response 200 (application/json)

        [
            {
                "character_id": 1
                "name": "Hoju",
                "title": "Count",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
            }
        ]

### Generate a New Character [POST]

You may generate new characters using this action.
This action takes a JSON payload, specifying the name of the character, as part of the request.
The response header contains the location of the newly generated character.
The response body contains full character data;
* new unique character_id,
* name given in the request,
* a noble title based on the character's social standing,
* randomly generated (2D roll) universal personality profile (UPP) with initial values from 2 to 12.

+ Request (application/json)

        {
            "name": "El Barto"
        }

+ Response 201 (application/json)

    + Headers

            Location: /characters/2

    + Body

            {
                "character_id": 2
                "name": "El Barto",
                "title": "Duke",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
            }

## Character [/characters/{character_id}]

+ Parameters
    + character_id (number) - ID of the Character in the form of an integer.

### View a Character's Detail [GET]

+ Response 200 (application/json)

        {
                "character_id": 2
                "name": "El Barto",
                "title": "Duke",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
        }

### Delete [DELETE]

+ Parameters
    + question_id (number) - ID of the Question in the form of an integer

### Delete [DELETE]

+ Response 204
