FORMAT: 1A

# travellerct

Travellerct is a simple API for generating, saving, and retrieving Traveller (CT) role playing game data.

## Characters Collection [/characters]

### List All Characters [GET]

List short form detail on all characters.

+ Response 200 (application/json)

        [
            {
                "character_id": 1
                "name": "Hoju",
                "title": "Count",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
            }
        ]

### Generate New Character [POST]

You may generate new characters using this action.
This action takes a JSON payload as part of the request.
Response then return specific header and body.

+ Request (application/json)

        {
            "name": "El Barto"
        }

+ Response 201 (application/json)

    + Headers

            Location: /characters/2

    + Body

            {
                "character_id": 2
                "name": "El Barto",
                "title": "Duke",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
            }

## Character [/characters/{character_id}]

+ Parameters
    + character_id (number) - ID of the Character in the form of an integer.

### View a Character's Detail [GET]

+ Response 200 (application/json)

        {
                "character_id": 2
                "name": "El Barto",
                "title": "Duke",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
        }
        
### Delete [DELETE]

+ Response 204