FORMAT: 1A

# travellerct

Travellerct is a simple API for generating and managing Classic Traveller (CT) role playing game data.

# Group Characters

Resources related to characters in the API.

## Character Collection [/characters]



### List All Characters [GET]

List full detail on all characters.
The universal personality profile (UPP) is represented by an integer from 1 to 15.

+ Response 200 (application/json)

        [
            {
                "character_id": 1
                "name": "Hoju",
                "title": "Count",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
            }
        ]

### Generate a New Character [POST]

You may generate new characters using this action.
This action takes a JSON payload, specifying the name of the character, as part of the request.
The response header contains the location of the newly generated character.
The response body contains full character data;
* new unique character_id,
* name given in the request,
* a noble title based on the character's social standing,
* randomly generated (2D roll) universal personality profile (UPP) with initial values from 2 to 12.

+ Request (application/json)

        {
            "name": "El Barto"
        }

+ Response 201 (application/json)

    + Headers

            Location: /characters/2

    + Body

            {
                "character_id": 2
                "name": "El Barto",
                "title": "Duke",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
            }

## Character [/characters/{character_id}]

+ Parameters
    + character_id (number) - ID of the Character in the form of an integer.

### View a Character's Detail [GET]

+ Response 200 (application/json)

        {
                "character_id": 2
                "name": "El Barto",
                "title": "Duke",
                "strength": 8,
                "dexterity": 8,
                "endurance": 8,
                "intelligence": 8,
                "education": 8,
                "social": 14
        }

### Update a Character's Detail [PUT]

+ Parameters
    + question_id (number) - ID of the Question in the form of an integer

### Update a Character's Detail [PUT]

+ Response 204

### Delete a Character [DELETE]

+ Parameters
    + question_id (number) - ID of the Question in the form of an integer

### Delete a Character [DELETE]

+ Response 204

# Data Structures

## Character (object)

+ character_id: 2 (number, required) - The unique identifier for a character.
+ name: El Barto (string, required) - Name of the character.
+ title: Duke (string) - Hereditary title.
+ strength: 8 (number) - Strength is both a general evaluation of the character's physical ability, and a specific measure of force which may be applied.
+ dexterity: 8 (number) - Dexterity measures physical coordination.
+ endurance: 8 (number) - Endurance measures physical determination and stamina.
+ intelligence: 8 (number) - Intelligence corresponds to IQ.
+ education: 8 (number) - Education indicates the highest level of schooling attained.
+ social: 14 (number) - Social Standing notes the social class and level of society from which the character comes.
